pi3a/pi3a/urls.py
from django.contrib import admin
from django.urls import include, path
from rh.views import UserProfileView

urlpatterns = [
    path("", UserProfileView.as_view(), name="home"),
    path("rh/", include("rh.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
]

pi3a/rh/urls.py
from django.urls import path
from rh.views import (
    TimesheetListView,
    TimesheetRegisterView,
    AddUserView,
    UserProfileView,
    AdminVacationsView,
    AddVacationView,
    AdminHorasExtrasView,
    DashboardView,
)


app_name = "rh"
urlpatterns = [
    path("usuarios", AddUserView.as_view(), name="user_register"),
    path("ferias", AdminVacationsView.as_view(), name="ferias_form"),
    path("ferias/add", AddVacationView.as_view(), name="ferias_register"),
    path("horas_extras", AdminHorasExtrasView.as_view(), name="horas_extras"),
    path("dashboard/<user_id>/<month>", DashboardView.as_view(), name="dashboard"),
    path(
        "user/profile",
        UserProfileView.as_view(template_name="rh/user_profile.html"),
        name="user_profile",
    ),
    path("timesheet/list", TimesheetListView.as_view(), name="timesheet_list"),
    path(
        "timesheet/register", TimesheetRegisterView.as_view(), name="timesheet_register"
    ),
]

pi3a/rh/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Time_sheet(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=300, blank=True)
    fk_user = models.ForeignKey(
        User, related_name="user_registro", on_delete=models.PROTECT
    )
    type = models.CharField(max_length=50, default="Entrada")


class Vacations(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    confirmed = models.BooleanField(default=True)
    fk_user = models.ForeignKey(
        User, related_name="user_ferias", on_delete=models.PROTECT
    )
    type = models.CharField(max_length=50, default="ferias")
    description = models.CharField(max_length=300, blank=True)


class Holidays(models.Model):
    description = models.CharField(max_length=300)
    day = models.CharField(max_length=2)
    month = models.CharField(max_length=2)
    year = models.CharField(max_length=4)


class NewUser(models.Model):
    pass

pi3a/rh/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Vacations, Time_sheet


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "password1", "password2"]


class VacationForm(ModelForm):
    class Meta:
        model = Vacations
        fields = "__all__"


class TimesheetForm(ModelForm):
    class Meta:
        model = Time_sheet
        fields = ["fk_user"]

pi3a/rh/views.py
import datetime
import calendar
from django.views.generic import TemplateView, ListView, View
from django.views.generic.edit import CreateView
from .forms import UserForm, VacationForm, TimesheetForm
from .models import User, Time_sheet, Holidays, Vacations
from django.http import JsonResponse


class UserProfileView(TemplateView):
    context_object_name = "user_profile"
    template_name = "rh/user_profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacations"] = self.get_user_vacation()
        context["last_registers"] = self.get_recently_user_timesheet()
        context["holiday"] = self.get_holiday()
        return context

    def get_user_vacation(self):
        if self.request.user.is_authenticated:
            # get last vacation register
            vacation = (
                Vacations.objects.filter(fk_user=self.request.user, confirmed=True)
                .order_by("-id")
                .last()
            )
            return vacation
        return None

    def get_recently_user_timesheet(self):
        if self.request.user.is_authenticated:
            # get last 5 timesheet register
            last_registers = Time_sheet.objects.filter(
                fk_user=self.request.user
            ).order_by("-created_at")[:5][::-1]
            return last_registers
        return None

    def get_holiday(self):
        today = datetime.datetime.today()
        current_year = today.year
        current_month = today.month
        current_day = today.day

        holidays = Holidays.objects.filter(
            year=current_year, month=current_month, day=current_day
        )

        if holidays.exists():
            return holidays.last()
        return None


class AddUserView(CreateView):
    form_class = UserForm
    template_name = "rh/user_register.html"
    success_url = "rh/usuarios/"


class AdminVacationsView(TemplateView):
    template_name = "rh/ferias.html"
    model = Vacations

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["users"] = User.objects.all()
        return context


class AddVacationView(CreateView):
    form_class = VacationForm
    success_url = "/rh/ferias"
    template_name = "rh/ferias.html"


class TimesheetRegisterView(CreateView):
    form_class = TimesheetForm
    success_url = "/rh/user/profile"
    template_name = "rh/timesheet_list.html"

    def form_valid(self, form):
        last_register = (
            Time_sheet.objects.filter(fk_user=self.request.user).order_by("id").last()
        )
        if last_register is None or last_register.type == "Saída":
            type = "Entrada"
        else:
            type = "Saída"
        form.instance.type = type
        return super().form_valid(form)


class AdminHorasExtrasView(TemplateView):
    template_name = "rh/horas_extras.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["users"] = User.objects.all()
        return context


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        # get request params
        user_id = int(kwargs["user_id"])
        month = kwargs["month"]
        input_dt = month.split("-")

        # get month last day do filter query
        period = calendar.monthrange(int(input_dt[0]), int(input_dt[1]))
        start_date = input_dt[0] + "-" + input_dt[1] + "-01"
        end_date = input_dt[0] + "-" + input_dt[1] + "-" + str(period[1])

        # query using date range and user
        times_query = Time_sheet.objects.filter(
            fk_user_id=user_id, created_at__range=[start_date, end_date]
        ).order_by("created_at")

        # variables used inside loop to format chart
        datasets = []
        last_day = None
        last_time = None
        result_dict = {}
        extra_hours = 0
        for times in times_query:
            day = times.created_at.date()
            time = times.created_at.time()
            if day == last_day:
                if last_time is not None:
                    diff = datetime.datetime.combine(
                        datetime.date.today(), time
                    ) - datetime.datetime.combine(datetime.date.today(), last_time)
                    result_dict[str(day)] += diff / datetime.timedelta(hours=1)
                    last_time = time
            else:
                last_day = day
                last_time = time
                result_dict[str(day)] = 0

        # format the value as a float with 2 decimal places
        for day, value in result_dict.items():
            result_dict[day] = "{:.2f}".format(value)

        # calculate extra_hours
        for day, value in result_dict.items():
            if float(value) > 8:
                extra_hours += float(value) - 8
        extra_hours = "{:.2f}".format(extra_hours)

        data = {
            "labels": list(result_dict.keys()),
            "datasets": [
                {
                    "label": "Horas trabalhadas",
                    "backgroundColor": "#28734e",
                    "borderColor": "#28734e",
                    "data": list(result_dict.values()),
                }
            ],
            "extra_hours": extra_hours,
        }

        return JsonResponse({"data": data})


class TimesheetListView(ListView):
    template_name = "rh/timesheet_list.html"
    context_object_name = "timesheet_list"

    def get_queryset(self):
        queryset = Time_sheet.objects.all()
        if self.request.user.is_authenticated:
            Time_sheet.objects.filter(fk_user=self.request.user)
        return queryset

pi3a/rh/templates/rh/ferias.html
{% extends 'base/base_lateral_header.html' %}

{% load static %}

{% block 'link' %}

<link rel="stylesheet" href="{% static 'rh/css/style_ferias.css' %}">
<link rel="stylesheet" href="{% static 'rh/css/style_global.css' %}">
{% endblock %}

{% block title %}Férias{% endblock %}

{% block content %}

<section class="content">
    <div class="box">
        <div class="box_ferias_titulo">
            <h4 class="box__titulo__principal">Registro de Férias e Afastamento</h4>
        </div>
        <div class="box_ferias_form">
            <form id="form_ferias" method="post" action="{% url 'rh:ferias_register' %}">
                {% csrf_token %}
                
                <div class="ferias__campos">
                    <div class="campos">
                        <h4 class="form__campos__titulo">Adicionar Período de Férias ou Afastamento</h4>
                        <div>
                            <select name="fk_user" id="selecao">
                                {% for user in users %}
                                    <option value="{{ user.id }}"> {{ user.first_name}} </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form_ferias__radio_button__tipo" style="margin-top: 16px;">
                            <label>Tipo*</label>
                            <div style="display: flex; gap:13px; margin-top: 13px;">

                                <div>
                                    <input type="radio" name="type" id="ferias" value="ferias" checked>
                                    <label for="ferias">Férias</label>
                                </div>

                                <div>
                                    <input type="radio" name="type" value="afastamento" id="afastamento">
                                    <label for="afastamento">Afastamento</label>
                                </div>

                            </div>
                        </div>

                        <div class="form_ferias__datas">

                            <div>
                                <label for="">Data ínicio*</label>
                                <input class="ferias__form__campos__date" type="date" name="start_date">
                            </div>

                            <div>
                                <label for="">Data de término</label>
                                <input class="ferias__form__campos__date" type="date" name="end_date">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ferias__textarea">
                    <div class="descricao">
                        <label for="descricao">Notas*</label>
                        <textarea name="description" id="descricao" cols="30" rows="10"></textarea>
                    </div>
                </div>
        </div>
        <div class="box_ferias_buttons">
            <button type="submit" style="width: 100%; 
            height: 2.5rem;" class="btn btn_green btn_ferias">Registrar</button>
        </div>
    </form>
</div>
    </div>
</section>


{% endblock %}

pi3a/rh/templates/rh/home_user.html
{% extends 'base/base_page_header.html' %}

{% load static %}

{% block title %} Home - User {% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'rh/css/style_home_user.css' %}">

    <aside class="side">
            <div class="lateral_link_meu_perfil">
                <img class="img_aside" src="{% static 'rh/img/noun-user-home-user.svg' %}" alt="">
                <a href="#" style="margin-left: 0.5625rem;">Meu Perfil</a>
            </div>
            <div class="lateral_link_sair" style="margin-top: 0.9375rem;">
                <img class="img_aside" src="{% static 'rh/img/sair-registros.svg' %}" alt="">
                <a href="#" style="margin-left: 0.5625rem;">Sair</a>
            </div>
    </aside>
    
    <section  class="content">
        <div class="agrupa_meu_perfil">
            <h3>Meu Perfil</h3>
            <div class="meu_perfil">
                <div class="home_admin_information">
                    <h3>Nome do Usuário</h3>
                    <p>CPF:111.111.111-00</p>
                    <p>Turno:9:00 - 18:00</p>
                    <div class="periodo_ferias">
                        <p>Ferias de 05/04/2023 a 20/04/2023</p>
                    </div>
                </div>
                <div class="home_admin_button">
                    <button class="btn_user_home" type="submit">Registrar Ponto</button>
                    <div class="home_admin_time">
                        <img src="" alt="">
                        <p>Previsão de Saída</p>
                        <p>00:00</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="agrupa_lista_registros">
            <h3>Últimos Registros</h3>
            <div class="lista_registros">
                <li>Registro 1</li>
                <li>Registro 2</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
                <li>Registro 3</li>
            </div>
        </div>

    </section>

{% endblock %}

pi3a/rh/templates/rh/horas_extras.html
{% extends 'base/base_lateral_header.html' %}

{% load static %}
{% block 'link' %}
<link rel="stylesheet" href="{% static 'rh/css/style_horas_extras.css' %}">
{% endblock %}

{% block title %} Horas Extras {% endblock %}

{% block content %}
<section class="content">

    <div class="box">
        <h3>Horas Extras</h3>
        <div class="group_horas_extras">
            <div class="box_horas_extras">

                <div class="selecao__contador">
                    <div class="selecao">
                        <h4>Relatório de Horas Extras</h4>
                        <form id="filterForm" > 
                            <select name="user_input" id="user_input">
                                {% for user in users %}
                                    <option value="{{ user.id }}"> {{ user.first_name}} </option>
                                {% endfor %}
                            <input name="month_input" id="month_input" type="month"  placeholder="Selecione o mês desejado">
                            <input type="submit" value="Buscar" name="_load">
                        </form>

                    </div>

                    <div class="box_contador">
                        <img class="clock" src="{% static 'rh/img/time-left1clock.svg' %}" alt="">
                        <p style="text-transform: uppercase; color: #FFFF;">Horas Extras</p>
                        <div class="contador">
                            <p id="extra_hours">00:00</p>
                        </div>
                    </div>

                </div>

                <div class="area__grafico">
                    <canvas id="chart" height="100"></canvas>
                </div>
            </div>

        </div>
    </div>

</section>
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"> </script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
<script>
    let extra_hours = "00:00"
    let today = new Date();
    let month = today.getMonth() + 1;
    let year = today.getFullYear();
    let month_input = document.getElementById("month_input");
    month = (month < 10 ? '0' : '') + month;
    month_input.defaultValue=year + "-" + month;

    let ctx = document.getElementById("chart").getContext("2d");
    let chart = new Chart(ctx, {
    type: "bar",
    options: {
        title: {
            text: "Horas trabalhadas",
            display: false
        }
    }
    });


  $("#filterForm").on("submit", (event) => {
    event.preventDefault();

    const month = $("#month_input").val();
    const user = $("#user_input").val();
    loadChart(month,user);
  });

  function loadChart(month, user) {
    $.ajax({
      url: `/rh/dashboard/${user}/${month}`,
      type: "GET",
      dataType: "json",
      success: (jsonResponse) => {
        // Extract data from the response
        const labels = jsonResponse.data.labels;
        const datasets = jsonResponse.data.datasets;
        const extra_hours = jsonResponse.data.extra_hours;
        // Reset the current chart
        chart.data.datasets = [];
        chart.data.labels = [];
        
        // Load new data into the chart
        chart.options.title.display = true;
        chart.data.labels = labels;
        datasets.forEach(dataset => {
            chart.data.datasets.push(dataset);
        });
        chart.update();
        extra_hours = document.getElementById("extra_hours").innerHTML=extra_hours

      },
      error: () => console.log("Failed to fetch chart data from " + endpoint + "!")
    });
  }

</script>

{% endblock %}

pi3a/rh/templates/rh/timesheet_list.html
{% extends 'base.html' %}
{% block title %}Registro de Ponto{% endblock %}
{% block content %}

<head>
    <title>REGISTRO PONTO</title>
</head>

<body>
    <h1>Meus registros</h1>
    <ul>
        {% for time in timesheet_list %}
        <li>{{time.created_at}}</li>
        <li>{{time.fk_user.first_name}}</li>
        <li>{{time.description}}</li>
        {% endfor %}
    </ul>

</body>

{% endblock %}

pi3a/rh/templates/rh/user_detail.html
<html>
<head>
<title>User Form</title>
</head>
<body>
<form>
<label for="name">Name:</label>
<input type="text" id="name" name="name"  required><br>

<label for="email">Email:</label>
<input type="email" id="email" name="email" required><br>

<label for="password">Password:</label>
<input type="password" id="password" name="password" minlength="8" required><br>

<label for="dob">Date of Birth:</label>
<input type="date" id="dob" name="dob" required><br>

<label for="gender">Gender:</label>
<label><input type="radio" id="gender" name="gender" value="male" required>Male</label>
<label><input type="radio" id="gender" name="gender" value="female" required>Female</label><br>
<br>

<label for="comments">Comments:</label>
<textarea id="comments" name="comments" rows="4" cols="50"></textarea><br>

<input type="submit" value="Submit">
</form>
</body>
</html>

pi3a/rh/templates/rh/user_home.html
{% extends 'base_page_no_header.html' %}
{% load static %}

{% block title %}Home Usuário{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<link rel="stylesheet" href="{% static 'rh/css/global.css' %}">
<link rel="stylesheet" href="{% static 'rh/css/style_user_home.css' %}">

	<!-- <h2>Hi {{ user.username }}!</h2> -->

	<!-- <h1>Welcome to Don't Get Fired</h1> -->
	<section id="pagina_user_home">
		<div class="form_home_user_option_list">
			<div class="box">
				<h2>SELECIONE UMA OPÇÃO</h2>
				<nav>
					<ul>
						<li><a href="#">MEU PERFIL</a></li>
						<li><a href="{% url 'rh:users'%}">CADASTRO</a></li>
						<li><a href="{% url 'rh:timesheet_list'%}">REGISTRO DE FÉRIAS</a></li>
						<li><a href="{% url 'rh:users' %}"></a>HORAS EXTRAS</li>
						<li>
							<p><a href="{% url 'logout' %}">Log Out</a></p>
							{% else %}
							<p>You are not logged in</p>
							<a href="{% url 'login' %}">Log In</a>
							{% endif %}
						</li>
						
					</ul>
				</nav>
			</div>
		</div>
	
		<div class="logo_home_user">
			<img src="{% static 'rh/img/logo-home-admin.svg' %}" alt="">
		</div>
	</section>
{% endblock %}

pi3a/rh/templates/rh/user_profile.html
{% extends 'base/base_lateral_header.html' %}

{% load static %}

{% block title %}Perfil Usuário {% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'rh/css/style_home_user.css' %}">

<section class="content">
    <div class="agrupa_meu_perfil">
        <h3 class="user__titulo__profile">Meu Perfil</h3>
        <div class="meu_perfil">
            <div class="home_admin_information">
                <h3 id="user__name">{{user.username}} {{user.first_name}} {{ user.last_name}}</h3>
                <p class="user__information">CPF: {{ user.username }}</p>
                <p class="user__information" id="turno__trabalho">Turno:9:00 - 18:00</p>
                {% if vacations %}
                <div class="periodo_ferias">
                    <p> Férias de {{vacations.start_date|date:"d/m/Y"}} a {{vacations.end_date|date:"d/m/Y"}}</p>
                </div>
                {% else %}
                <div class="periodo_ferias">
                    <img style="margin-left: 20px;" src="{% static 'rh/img/calendar.png' %}" alt="">
                    <p> Férias de {{vacations.start_date|date:"d/m/Y"}} a {{vacations.end_date|date:"d/m/Y"}}</p>
                </div>
                {% endif %}

            </div>
            <div class="home_admin_button">
                <form method="post" action="{% url 'rh:timesheet_register' %}">
                    {% csrf_token %}
                    <button class="btn_user_home" type="submit" name="fk_user" value={{ user.id }}>Registrar Ponto</button>
                </form>
                <div class="home_admin_time">
                    <img src="{% static 'rh/img/time-left1clock.svg' %}" alt="">
                    <div class="tempos__saida">
                        <p id="texto_saida">Previsão de Saída</p>
                        <p id="relogio__user__profile">00:00</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="agrupa_lista_registros">
        <h3 class="user__titulo__profile">Últimos Registros</h3>
        <div class="lista_registros" style="margin-bottom: 10px;">
            {% for register in last_registers %}
            <li class="li__registro"><img src="{% static 'rh/img/sair-registros.svg' %}"> {{register.created_at|time:"H:i"}} |
                {{register.created_at|date:"d.m"}} |
                {{register.type}}
            </li>
            <hr style="max-width: 860px; margin-left: 20px;">
            {% endfor %}
        </div>
    </div>

</section>
 <script src="{% static '/js/index.js' %}"></script>

{% endblock %}

pi3a/rh/templates/rh/user_register.html
{% extends 'base/base_lateral_header_cadastro.html' %}

{% load static %}

{% block 'link' %}
<link rel="stylesheet" href="{% static 'rh/css/style_base_header.css' %}">
<link rel="stylesheet" href="{% static 'rh/css/style_register.css' %}">
<link rel="stylesheet" href="{% static 'rh/css/style_global.css' %}">
{% endblock %}

{% block title %}Cadastro de Usuários {% endblock %}

{% block content %}

<section class="content">
    <div class="agrupa_meu_perfil">
        <div class="meu_perfil" style="display: flex; flex-direction: column; align-self: center;">
            <div class="home_admin_information">

                <h2 id="titulo_registro_form">CADASTRO DE FUNCIONÁRIOS</h2>
                <form method="post" style="display: flex; flex-direction: column;">
                    {% csrf_token %}
                    
                    <input class="register__form__input" id="cpf" type="text" name="username" placeholder="N° CPF" required maxlength="11" minlength="11" onblur="validateCPF(this.value)" onchange="validateCPF(this.value)">
                    <span id="cpfInvalido" style="color: red; display: none;">Digite um cpf válido.</span>

                    <input class="register__form__input" type="text" name="first_name" placeholder="Nome" required maxlength="100" id="name" onblur="validateNome(this.value)" onchange="validateNome(this.value)">
                    <span id="nameInvalido" style="color: red; display: none;">Digite um nome válido.</span>

                    <input class="register__form__input" type="text" name="last_name" placeholder="Sobrenome" required maxlength="100" id="lastname" onblur="validateSobrenome(this.value)" onchange="validateSobrenome(this.value)">
                    <span id="sobrenomeInvalido" style="color: red; display: none;">Digite um sobrenome válido.</span>

                    <input class="register__form__input" type="password" name="password1" placeholder="Senha" required maxlength="100" minlength="8" id="pass" onblur="validateSenha(this.value)" onchange="validateSenha(this.value)">
                    <span id="senhaInvalida" style="color: red; display: none;">Digite uma senha válida.</span>

                    <input class="register__form__input" type="password" name="password2" placeholder="Repita a senha" required maxlength="100" minlength="8" id="pass_conf" onblur="validateSenhaConf(this.value)" onchange="validateSenhaConf(this.value)">
                    <span id="senhaConfInvalida" style="color: red; display: none;">Digite uma senha válida.</span>

                    <button onclick="validate" class="btn btn_user_home" type="submit" id="submit">Registrar </button>
                    <div class="buttons_register">
                    </div>
                </form>
            </div>

        </div>
    </div>

</section>
<!-- <script src="{% static 'rh/js/validate.js'  %}"></script> -->
<script src="{% static '/js/validate.js' %}"></script>

{% endblock %}

pi3a/templates/base/base_lateral_header.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if user.is_authenticated %}
    {% block 'link' %} 
    {% endblock %}
    <link rel="stylesheet" href="{% static 'rh/css/style_base_header.css' %}">
    <title>{% block title %} Don't Get Fired!  {% endblock %}</title>
</head>

<body>
    <header style="background-color: #28734E;">
        <h1 >
            <img style="margin-left: 1.5rem; padding: 0.875rem 0 0.875rem 0;" src="{% static 'rh/img/DGF_WHITE_LOGO.png' %}" alt="teste">
        </h1>
    </header>
    <main>

    <aside class="side">
            <div class="lateral_link_meu_perfil">
                <img class="img_aside" src="{% static 'rh/img/noun-user-home-user.svg' %}" alt="">
                <a href="{% url 'rh:user_profile'%}">Meu Perfil</a>
            </div>
            {% if user.is_staff %}
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/register-icons-lateral.svg' %}" alt="">
                    <a href="{% url 'rh:user_register'%}">Cadastro</a>
                </div>
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/icon-lateral-sun.svg' %}" alt="">
                    <a href="{% url 'rh:ferias_form'%}">Férias</a>
                </div>
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/time-icon-lateral.svg' %}" alt="">
                    <a href="{% url 'rh:horas_extras' %}">Horas Extras</a>
                </div>
            {% endif %}
            <div class="lateral_link_meu_perfil" >
                <img class="img_aside" src="{% static 'rh/img/sair-registros.svg' %}" alt="">
                <a href="{% url 'logout' %}">Sair</a>
            </div>
    </aside>
    
    {% block content %}
    {% endblock %}
    {% endif %}
</main>
</body>

</html>

pi3a/templates/base/base_lateral_header_cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block 'link' %} 
    {% endblock %}
    <link rel="stylesheet" href="{% static 'rh/css/style_base_header_cadastro.css' %}">
    <title>{% block title %} Don't Get Fired!  {% endblock %}</title>
</head>

<body>
    <header style="background-color: #28734E;">
        <h1 >
            <img style="margin-left: 1.5rem; padding: 0.875rem 0 0.875rem 0;" src="{% static 'rh/img/DGF_WHITE_LOGO.png' %}" alt="teste">
        </h1>
    </header>
    <main>

    <aside class="side">
            <div class="lateral_link_meu_perfil">
                <img class="img_aside" src="{% static 'rh/img/noun-user-home-user.svg' %}" alt="">
                <a href="{% url 'rh:user_profile'%}">Meu Perfil</a>
            </div>
            {% if user.is_staff %}
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/register-icons-lateral.svg' %}" alt="">
                    <a href="{% url 'rh:user_register'%}">Cadastro</a>
                </div>
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/icon-lateral-sun.svg' %}" alt="">
                    <a href="{% url 'rh:ferias_form'%}">Férias</a>
                </div>
                <div class="lateral_link_meu_perfil">
                    <img class="img_aside" src="{% static 'rh/img/time-icon-lateral.svg' %}" alt="">
                    <a href="{% url 'rh:horas_extras' %}">Horas Extras</a>
                </div>
            {% endif %}
            <div class="lateral_link_meu_perfil" >
                <img class="img_aside" src="{% static 'rh/img/sair-registros.svg' %}" alt="">
                <a href="{% url 'logout' %}">Sair</a>
            </div>
    </aside>
    
    {% block content %}
    {% endblock %}
</main>
</body>

</html>